---
# revealjs-plugins:
#   - editable
# filters:
#   - editable
---

# [Part 5] more things

## Cleaning up
You can delete the "local" repo (It’s just a regular directory on your computer).

Note, if you are doing it in the shell, use:
``` sh
rm -rf <YOUR-REPOSITORY>
```
`-rf` will save you some time saying "yes" delete this hidden git file a gazillion times

Then, in the browser, go to your repo’s landing page on `GitHub` > Click on *Settings* > Scroll down, click on *delete repository* and do as it asks.

## Comparing versions

git diff

## Fun facts 
The `GitHub` mascot is named **Octocat**, a `merge` between an octopuss and cat. 

Do you know the story behind this logo creation?

The idea came from the “octopus merge” – the practice of combining three or more branches of development. The logo was created by Simon Oxley, who doesn't remember creating it, apparently. Initially, Simon thought of calling his creation *"Octopuss"* (combination of octopus and pussycat) to represent how complex code combines can create peculiar things. 

In the end, `GitHub` decided to go with *Octocat* (for obvious reasons).

## Conclusions and goodbyes
The workflows described here are widely regarded as current best practice, yet we generally neither practice nor preach it in academic settings.

Now just “lather, rinse, repeat”. Do work somewhere: locally or on GitHub. Commit it. Push it or pull it, depending on where you did the work, get local and remote “synced up”. Repeat.

## Resources
[Bryan, J. (2018)](https://doi.org/10.1080/00031305.2017.1399928). Excuse Me, Do You Have a Moment to Talk About Version Control? *The American Statistician*, 72(1), 20–27.
